# Generated by Django 3.1.4 on 2020-12-28 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recurso', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Lista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lista.tipo_lista')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'id')},
            },
        ),
        migrations.CreateModel(
            name='Lista_Libro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lista.lista')),
                ('recurso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recurso.recurso')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('lista', 'recurso')},
            },
        ),
    ]
