# Generated by Django 3.1.4 on 2021-01-05 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recurso', '0011_auto_20210104_2051'),
        ('lista', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='recurso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recurso.recurso'),
        ),
    ]
