# Generated by Django 3.1.4 on 2020-12-16 06:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lista', '0002_lista_usuario'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lista',
            unique_together={('usuario', 'id')},
        ),
    ]
