# Generated by Django 3.1.4 on 2020-12-23 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recurso', '0004_recurso_imagen'),
        ('lista', '0003_auto_20201216_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibroLista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lista.lista')),
                ('recurso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recurso.recurso')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('lista', 'recurso')},
            },
        ),
    ]
