# Generated by Django 3.1.4 on 2020-12-24 20:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recurso', '0005_recurso_archivo'),
        ('lista', '0004_librolista'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LibroLista',
            new_name='Lista_Libro',
        ),
    ]
