# Generated by Django 3.1.4 on 2020-12-27 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0005_auto_20201224_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
