# Generated by Django 3.1.4 on 2020-12-28 02:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='RecursoArchivo',
            fields=[
                ('recurso_archivo_pk', models.AutoField(primary_key=True, serialize=False)),
                ('bytes', models.BinaryField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RecursoImagen',
            fields=[
                ('recurso_imagen_pk', models.AutoField(primary_key=True, serialize=False)),
                ('bytes', models.BinaryField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Recurso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=250)),
                ('descripcion', models.CharField(max_length=250)),
                ('anyo_publicacion', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2020)])),
                ('autor', models.CharField(max_length=250)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('imagen', models.ImageField(blank=True, default=None, null=True, upload_to='recurso.RecursoPicture/bytes/filename/mimetype')),
                ('archivo', models.FileField(blank=True, default=None, null=True, upload_to='recurso.RecursoArchive/bytes/filename/mimetype')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recurso.categoria')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recurso.tipo_recurso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'id')},
            },
        ),
    ]
