# Generated by Django 3.1.4 on 2020-12-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurso', '0002_auto_20201227_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='archivo',
            field=models.FileField(blank=True, default=None, upload_to='recurso.RecursoArchivo/bytes/filename/mimetype'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='imagen',
            field=models.ImageField(blank=True, default=None, upload_to='recurso.RecursoImagen/bytes/filename/mimetype'),
        ),
    ]
