# Generated by Django 3.1.4 on 2020-12-23 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurso', '0004_recurso_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='archivo',
            field=models.FileField(blank=True, upload_to='files'),
        ),
    ]
