# Generated by Django 3.1.4 on 2020-12-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurso', '0005_auto_20201228_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursoarchivo',
            name='filename',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='recursoimagen',
            name='filename',
            field=models.CharField(max_length=500),
        ),
    ]
