# Generated by Django 3.1.4 on 2020-12-27 01:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurso', '0005_recurso_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurso',
            name='year',
        ),
        migrations.AddField(
            model_name='recurso',
            name='anyo_publicacion',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2020)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recurso',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
