# Generated by Django 3.1.4 on 2020-12-29 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recurso', '0007_auto_20201228_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='tipo_recurso',
            options={'ordering': ['nombre']},
        ),
    ]
