# Generated by Django 3.1.4 on 2020-12-31 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurso', '0008_auto_20201229_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
