# Generated by Django 3.1.4 on 2021-01-05 02:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurso', '0010_remove_recurso_removed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='anyo_publicacion',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2021)]),
        ),
    ]
